#!/usr/bin/env bun
/**
 * Schema Drift Verification Script
 *
 * Connects to the database and verifies that the live PostgreSQL schema matches
 * the authoritative contract generated by `supabase/migrations/*`.
 *
 * Validates:
 * - All tables, columns, nullability, data types
 * - Custom enums
 * - Primary keys & Foreign keys (with cascade rules)
 * - Unique constraints
 * - CHECK constraints (business invariants)
 * - Indexes (including partial & composite indexes)
 * - Triggers & Functions
 * - Row Level Security (RLS) enabled status
 * - RLS Policies
 */

import { postgres, verifySchemaAgainstContract } from "../packages/db/src/index";

import { assertRefsMatch, getDatabaseUrl, ScriptTargetError } from "./lib/target";

function getDatabaseUrlOrExit(): string {
  // Production is refused unless named explicitly and deliberately
  // (`--allow-production`); there is no environment-variable override.
  const allowProduction = process.argv.includes("--allow-production");
  try {
    assertRefsMatch(process.env, "the current environment");
    return getDatabaseUrl(process.env, { allowProduction });
  } catch (error) {
    if (error instanceof ScriptTargetError) {
      console.error(`❌ ${error.message}`);
      process.exit(1);
    }
    throw error;
  }
}

async function main() {
  const dbUrl = getDatabaseUrlOrExit();
  console.log("🔍 Running Database Schema Drift Verification against:", dbUrl.replace(/:[^:@]+@/, ":***@"));

  const sql = postgres(dbUrl, { prepare: false, max: 1 });
  try {
    const result = await verifySchemaAgainstContract(sql);

    if (!result.ok) {
      console.error("\n❌ SCHEMA DRIFT DETECTED! The following database objects do not match the expected contract:\n");
      for (const err of result.errors) {
        console.error(`  - ${err}`);
      }
      console.error(`\nTotal schema drift violations: ${result.errors.length}\n`);
      process.exit(1);
    }

    console.log("\n✅ SCHEMA VERIFICATION PASSED. Zero drift detected.\n");
    console.table(result.summary);
  } catch (err) {
    console.error("❌ Failed to verify database schema:", err);
    process.exit(1);
  } finally {
    await sql.end();
  }
}

main();
